apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/services/profile.yaml
  - ../../apps/services/mentor.yaml
  - ../../apps/services/identity.yaml
  - ../../apps/infrastructure/chaos-mesh.yaml
  - ../../apps/infrastructure/chaos-experiments.yaml

patches:
  - path: values/profile.yaml
  - path: values/mentor.yaml
  - path: values/identity.yaml
