apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/services/profile.yaml
  - ../../apps/services/mentor.yaml
  - ../../apps/services/identity.yaml

# Cloud-specific patches will be added as services are deployed
